Repository Les-Dalbayobs/easySave, pull requests merged in 2022-02, with the labels that each got.

#29 create-title
  easySave/Views/view.cs
Labels: enhancement

#30 Added the bases for the graphic version
  easySave - Graphic/App.xaml
  easySave - Graphic/App.xaml.cs
  easySave - Graphic/AssemblyInfo.cs
  easySave - Graphic/ViewModel/viewModel.cs
  easySave - Graphic/Views/MainWindow.xaml
  easySave - Graphic/Views/MainWindow.xaml.cs
  easySave - Graphic/easySave - Graphic.csproj
  easySave - Graphic/easySave_Graphic.csproj
  easySave.sln
  easySave/Models/job.cs
Labels: enhancement

#31 create-main-window
  easySave - Graphic/Views/MainWindow.xaml
  easySave - Graphic/Views/MainWindow.xaml.cs
  easySave - Graphic/Views/dalbayos logo$.png
  easySave - Graphic/easySave - Graphic.csproj
Labels: enhancement

#32 Implementation of language changes
  easySave - Graphic/App.xaml.cs
  easySave - Graphic/Properties/Resources.Designer.cs
  easySave - Graphic/Properties/Resources.fr.resx
  easySave - Graphic/Properties/Resources.resx
  easySave - Graphic/Properties/Settings.Designer.cs
  easySave - Graphic/Properties/Settings.settings
  easySave - Graphic/Settings.cs
  easySave - Graphic/Views/MainWindow.xaml
  easySave - Graphic/Views/MainWindow.xaml.cs
  easySave - Graphic/Views/WindowLang.xaml
  easySave - Graphic/Views/WindowLang.xaml.cs
  easySave - Graphic/easySave - Graphic.csproj
Labels: enhancement

#33 Job display
  easySave - Graphic/ViewModel/MainWindowsViewsModel.cs
  easySave - Graphic/ViewModel/viewModel.cs
  easySave - Graphic/Views/MainWindow.xaml
  easySave - Graphic/Views/MainWindow.xaml.cs
  easySave - Graphic/easySave - Graphic.csproj
  easySave/ViewModel/viewModel.cs
Labels: enhancement

#36 Job creation functionality
  easySave - Graphic/ViewModel/MainWindowsViewsModel.cs
  easySave - Graphic/Views/CreatJob.xaml
  easySave - Graphic/Views/CreatJob.xaml.cs
  easySave - Graphic/Views/MainWindow.xaml
  easySave - Graphic/Views/MainWindow.xaml.cs
  easySave - Graphic/easySave - Graphic.csproj
Labels: enhancement, Graphical

#35 Create-Delete-Window
  easySave - Graphic/Pictures/icons8-warning-48.png
  easySave - Graphic/Views/DeleteJob.xaml
  easySave - Graphic/Views/DeleteJob.xaml.cs
  easySave - Graphic/Views/icons8-warning-48.png
Labels: enhancement, Graphical

#44 Delete function
  easySave - Graphic/ViewModel/MainWindowsViewsModel.cs
  easySave - Graphic/Views/DeleteJob.xaml
  easySave - Graphic/Views/DeleteJob.xaml.cs
  easySave - Graphic/Views/MainWindow.xaml
  easySave - Graphic/Views/MainWindow.xaml.cs
  easySave - Graphic/icons8-warning-48.png
Labels: enhancement, Graphical

#45 Edit function
  easySave - Graphic/Views/MainWindow.xaml.cs
Labels: enhancement, Graphical

#46 Deactivation of dataGrid editing
  easySave - Graphic/Views/MainWindow.xaml
Labels: bug, Graphical

#47 Feat gra save menu design
  easySave - Graphic/Pictures/playpause.png
  easySave - Graphic/Pictures/stop.png
  easySave - Graphic/Views/MainWindow.xaml
  easySave - Graphic/Views/MainWindow.xaml.cs
  easySave - Graphic/Views/saveMenu.xaml
  easySave - Graphic/Views/saveMenu.xaml.cs
Labels: enhancement, Graphical

#52 Save and recovery jobs
  easySave - Graphic/ViewModel/MainWindowsViewsModel.cs
  easySave - Graphic/Views/MainWindow.xaml.cs
Labels: enhancement, Graphical

#53 Create window of encryption
  easySave - Graphic/Views/EncryptionWindow.xaml
  easySave - Graphic/Views/EncryptionWindow.xaml.cs
  easySave - Graphic/Views/MainWindow.xaml
  easySave - Graphic/Views/MainWindow.xaml.cs
Labels: enhancement, Graphical

#54 Preparation v2
  easySave - Graphic/Properties/Resources.Designer.cs
  easySave - Graphic/Properties/Resources.fr.resx
  easySave - Graphic/Properties/Resources.resx
  easySave - Graphic/Views/CreatJob.xaml
  easySave - Graphic/Views/DeleteJob.xaml
  easySave - Graphic/Views/EncryptionWindow.xaml
  easySave - Graphic/Views/MainWindow.xaml
  easySave - Graphic/Views/MainWindow.xaml.cs
  easySave - Graphic/Views/saveMenu.xaml
Labels: enhancement, Graphical

#56 Full trad + remake the save menu design
  easySave - Graphic/Properties/Resources.Designer.cs
  easySave - Graphic/Properties/Resources.fr.resx
  easySave - Graphic/Properties/Resources.resx
  easySave - Graphic/Views/CreatJob.xaml
  easySave - Graphic/Views/DeleteJob.xaml
  easySave - Graphic/Views/DeleteJob.xaml.cs
  easySave - Graphic/Views/EncryptionWindow.xaml
  easySave - Graphic/Views/MainWindow.xaml
  easySave - Graphic/Views/MainWindow.xaml.cs
  easySave - Graphic/Views/saveMenu.xaml
  easySave - Graphic/Views/saveMenu.xaml.cs
  easySave - Graphic/easySave - Graphic.csproj
Labels: enhancement, Graphical

#58 Enhanced edit and create function
  easySave - Graphic/ViewModel/MainWindowsViewsModel.cs
  easySave - Graphic/Views/CreatJob.xaml
  easySave - Graphic/Views/CreatJob.xaml.cs
  easySave - Graphic/Views/MainWindow.xaml.cs
  easySave/Models/job.cs
  easySave/ViewModel/viewModel.cs
Labels: bug, enhancement, Graphical

#61 Encryption
  easySave - Graphic/Properties/Settings.Designer.cs
  easySave - Graphic/Properties/Settings.settings
  easySave - Graphic/ViewModel/MainWindowsViewsModel.cs
  easySave - Graphic/Views/EncryptionWindow.xaml
  easySave - Graphic/Views/EncryptionWindow.xaml.cs
  easySave - Graphic/Views/MainWindow.xaml
  easySave - Graphic/Views/MainWindow.xaml.cs
  easySave - Graphic/Views/saveMenu.xaml.cs
  easySave/Models/job.cs
  easySave/Models/logProgressSave.cs
Labels: enhancement, Graphical

#67 Progress bar jobs
  easySave - Graphic/Models/job.cs
  easySave - Graphic/ViewModel/MainWindowsViewsModel.cs
  easySave - Graphic/Views/MainWindow.xaml.cs
  easySave - Graphic/Views/saveMenu.xaml
  easySave - Graphic/Views/saveMenu.xaml.cs
  easySave - Graphic/easySave - Graphic.csproj
Labels: enhancement, Graphical

#69 Log xml integration
  easySave - Graphic/Models/job.cs
  easySave - Graphic/Models/logProgressSave.cs
  easySave - Graphic/Properties/Resources.Designer.cs
  easySave - Graphic/Properties/Resources.fr.resx
  easySave - Graphic/Properties/Resources.resx
  easySave - Graphic/Properties/Settings.Designer.cs
  easySave - Graphic/Properties/Settings.settings
  easySave - Graphic/Views/MainWindow.xaml.cs
  easySave - Graphic/Views/settings.xaml
  easySave - Graphic/Views/settings.xaml.cs
Labels: enhancement, Graphical

#75 Parallel copy
  easySave - Graphic/Models/job.cs
  easySave - Graphic/Models/jobThread.cs
  easySave - Graphic/Views/saveMenu.xaml
  easySave - Graphic/Views/saveMenu.xaml.cs
Labels: enhancement, Graphical

#78 Mono instance
  easySave - Graphic/App.xaml.cs
Labels: enhancement, Graphical

#77 Xml console
  easySave - Graphic/Models/job.cs
  easySave/Models/job.cs
  easySave/Models/logProgressSave.cs
  easySave/Resources/strings.en.resx
  easySave/Resources/strings.fr.resx
  easySave/ViewModel/viewModel.cs
  easySave/Views/view.cs
Labels: enhancement, Console

#80 delete title bar of the main windows and create drag
  easySave - Graphic/App.xaml.cs
  easySave - Graphic/Views/CreatJob.xaml.cs
  easySave - Graphic/Views/DeleteJob.xaml.cs
  easySave - Graphic/Views/MainWindow.xaml
  easySave - Graphic/Views/MainWindow.xaml.cs
  easySave - Graphic/Views/WindowLang.xaml.cs
  easySave - Graphic/Views/saveMenu.xaml.cs
  easySave - Graphic/Views/settings.xaml.cs
Labels: enhancement, Graphical

#81 Create new console project
  EasyConsole/App.xaml
  EasyConsole/App.xaml.cs
  EasyConsole/AssemblyInfo.cs
  EasyConsole/EasyConsole.csproj
  EasyConsole/MainWindow.xaml
  EasyConsole/MainWindow.xaml.cs
  easySave.sln
Labels: enhancement, Graphical

#79 File prioritization
  easySave - Graphic/Models/job.cs
  easySave - Graphic/Models/jobThread.cs
  easySave - Graphic/Properties/Resources.Designer.cs
  easySave - Graphic/Properties/Resources.fr.resx
  easySave - Graphic/Properties/Resources.resx
  easySave - Graphic/Properties/Settings.Designer.cs
  easySave - Graphic/Properties/Settings.settings
  easySave - Graphic/ViewModel/MainWindowsViewsModel.cs
  easySave - Graphic/Views/settings.xaml
  easySave - Graphic/Views/settings.xaml.cs
Labels: enhancement, Graphical

#82 Added max simultaneous file size into settings menu
  easySave - Graphic/Models/job.cs
  easySave - Graphic/Properties/Resources.Designer.cs
  easySave - Graphic/Properties/Resources.fr.resx
  easySave - Graphic/Properties/Resources.resx
  easySave - Graphic/Views/settings.xaml
Labels: enhancement, Graphical

#85 Max size
  easySave - Graphic/Models/job.cs
  easySave - Graphic/Models/jobThread.cs
  easySave - Graphic/Properties/Settings.Designer.cs
  easySave - Graphic/Properties/Settings.settings
  easySave - Graphic/ViewModel/MainWindowsViewsModel.cs
  easySave - Graphic/Views/MainWindow.xaml.cs
  easySave - Graphic/Views/saveMenu.xaml
  easySave - Graphic/Views/saveMenu.xaml.cs
  easySave - Graphic/Views/settings.xaml
  easySave - Graphic/Views/settings.xaml.cs
Labels: enhancement, Graphical

#87 Feat size max
  easySave - Graphic/Models/job.cs
Labels: enhancement, Graphical

#88 Enhanced Business Soft pause
  easySave - Graphic/Models/job.cs
  easySave - Graphic/Models/jobThread.cs
  easySave - Graphic/Properties/Resources.Designer.cs
  easySave - Graphic/Properties/Resources.fr.resx
  easySave - Graphic/Properties/Resources.resx
  easySave - Graphic/Views/saveMenu.xaml.cs
Labels: enhancement, Graphical

#86 Finish traduction and add comments
  easySave - Graphic/Models/job.cs
  easySave - Graphic/Properties/Resources.Designer.cs
  easySave - Graphic/Properties/Resources.fr.resx
Labels: enhancement, Graphical

#90 White to purple
  easySave - Graphic/Views/saveMenu.xaml
Labels: Graphical
